#%RAML 1.0 Library
usage: Use the following traits for pagination

traits:
  pageable: !include ../traits/pageable.raml
  searchablebypostcode: !include ../traits/searchablebypostcode.raml
  cacheable: !include ../traits/cacheable.raml
  